[book]
title = "1С как иностранный язык"
authors = ["Александр Мирошниченко"]
language = "ru"
src = "."

[output.html]
site-url = "/1c-inostrannyy-yazyk/"
git-repository-url = "https://github.com/iMironRU/1c-inostrannyy-yazyk"
edit-url-template = "https://github.com/iMironRU/1c-inostrannyy-yazyk/edit/main/{path}"
